import type { Movie, MoviesItems } from "pages/Movies/Movies.types";

export const testMovies: MoviesItems = {
  results: [
    {
      adult: false,
      backdrop_path: "/test2.jpg",
      genre_ids: [2],
      id: 2,
      original_language: "en",
      original_title: "title2",
      overview: "overview2",
      popularity: 2,
      poster_path: "/test2.jpeg",
      release_date: "2021-07-02",
      title: "title2",
      video: false,
      vote_average: 2,
      vote_count: 2,
      isFavorite: false,
    },
    {
      adult: false,
      backdrop_path: "/test3.jpg",
      genre_ids: [3],
      id: 3,
      original_language: "en",
      original_title: "title3",
      overview: "overview3",
      popularity: 3,
      poster_path: "/test3.jpeg",
      release_date: "2021-07-02",
      title: "title3",
      video: false,
      vote_average: 3,
      vote_count: 3,
      isFavorite: false,
    },
  ],
};

export const testMovie: Movie = {
  poster_path: "/randomString.jpg",
  adult: false,
  overview: "Random overview",
  release_date: "2021-05-05",
  genre_ids: [1],
  id: 1,
  original_title: "title",
  original_language: "en",
  title: "title",
  backdrop_path: "/randomString.jpg",
  popularity: 1,
  vote_count: 1,
  video: false,
  vote_average: 1,
  isFavorite: false,
};
